### ISSUE TITLE
Present SafariView on top most viewController

### ISSUE THREAD

**Issue by LouisBorlee** [SimplicityMobile/Simplicity#17]
Hi,

There seems to be no available way of presenting the SafariView if another viewController is already being presented.

Is that wanted or will it be changed?

Cordially, Louis.

**Comment by edjiang** [comment]
Hey @LouisBorlee:

Would love to hear your feedback on this conversation here:

https://github.com/SimplicityMobile/Simplicity/pull/10

I think we should definitely visit doing something like this; I'm just not too familiar with the edge cases around this at the moment.

**Comment by edjiang** [comment]
Hey @LouisBorlee, I believe #22 should fix your concerns. It's now pushed under 2.0.1. Let me know if this does not!

**Comment by LouisBorlee** [comment]
Hi @edjiang,

Thank you for your reply and update.

Sadly, I'm using your Swift 2.3 branch and thus can't use your fix.
I'll try to see what I can do later for I haven't the time to do it so for now.

Have a nice day!

**Comment by edjiang** [comment]
Ah kk. You could try modifying the dependency files and checking them in, as that branch will probably no longer be updated. Or, you can submit a PR to 2.3; it's like another 4 lines of code so should be fairly straightforward either way =]
