### ISSUE TITLE
I have everything setup, yet calling the login function appears to do nothing.

### ISSUE THREAD

**Issue by chuby1tubby** [SimplicityMobile/Simplicity#20]
I called the function 'Simplicity.login(Google())' within my viewDidLoad() function in the ViewController.swift file.

I expected something to happen when I tried to print the accessToken within the function's scope, yet nothing happens when the code runs. There's no errors so I'd like to know what step I'm missing.

Thanks!

**Comment by edjiang** [comment]
Hey @chuby1tubby -- is the google login page even appearing?

You most likely need to put this in the `viewDidAppear` function.

**Comment by chuby1tubby** [comment]
Oh! I'm sorry I don't know why I didn't try that first.
That made the login screen appear, so thank you.

Now, does the user have to input their login credentials every single time they open my app? Or can the Google account stay logged in indefinitely?

**Comment by edjiang** [comment]
It's up to you for how you want to save the access token returned; Simplicity does not handle that for you. I would recommend saving it into the iOS Keychain.

**Comment by edjiang** [comment]
In other apps, you might want to use the Google token to log into your own server. In that case, you can do that however you want, too =]

**Comment by chuby1tubby** [comment]
Great. Thank you for that information! I'm super excited to use this in many apps in the future.

**Comment by edjiang** [comment]
No problem! Glad we could help!
