### ISSUE TITLE
Issue regarding presenting safari viewcontroller from root view controller

### ISSUE THREAD

**Issue by Dharin-shah** [SimplicityMobile/Simplicity#23]
I have a login view controller that is presented modally which uses the simplicity. But since the root view controllers view is not currently on top of the window stack the system throws a warning that the view controller (safari) cannot be presented since the view is not visible. I did fix it. Do you mind if i issue a pull request.

**Comment by edjiang** [comment]
Sure! I think @pherret tried to fix it in #22 -- can you please see if that fixed it? Otherwise go for it!

**Comment by edjiang** [comment]
I believe this is solved now, since I can't replicate any issues here. If not, please reopen this issue!
