### ISSUE TITLE
Getting public_profile,email

### ISSUE THREAD

**Issue by Marini83** [SimplicityMobile/Simplicity#24]
Hello,

How would I go about getting public_profile and email? After I get the token I can get the "name" and "id" fields, but how would I go about getting the rest of that information? 

Thank you

**Comment by edjiang** [comment]
Definitely a great question! I have a duplicate issue open with a response and discussion of next steps, and if you want to check out the thread or comment, please do so =] Closing as duplicate. 

https://github.com/SimplicityMobile/Simplicity/issues/15
