### ISSUE TITLE
Modals and safaryViewController bug

### ISSUE THREAD

**Issue by Alex293** [SimplicityMobile/Simplicity#26]
Hi, 

I'm using modals in my projects and if I use simplicity to open the safariController It dismiss my modals so its not convenient from the user point of view. I've fixed it by adding : 

safari?.modalPresentationStyle = .overFullScreen

just before
topController?.present(safari!, animated: true, completion: nil)

in presentSafariView(_ url:) in Simplicity class

As safariView is present over full screen anyway I don't think there are drawbacks to do so. Can I have you point of view on this ?

**Comment by edjiang** [comment]
Yeah, it seems like right now how the views are presented can cause problems in certain hierarchies. Doesn't seem like your approach will have problems, though!

**Comment by edjiang** [comment]
Hey @Alex293, I'm trying to look into this again, and can't replicate when Simplicity will dismiss your modals for you. Perhaps I'm not thinking of the correct view hierarchy where it may accidentally do that. Can you please give me a way to reproduce your problem? Thanks!
