### ISSUE TITLE
Multiple app launch

### ISSUE THREAD

**Issue by Alex293** [SimplicityMobile/Simplicity#27]
Hi, Simplicity is working great in my project but what is the preferred way to store the token after getting it ? Can you provide a tiny sample ?

**Comment by edjiang** [comment]
Hey! Simplicity doesn't have a preference, and it's up to you how to store it. Many people will exchange it for a token in their own backend, and store it in the Keychain. You could try a Keychain wrapper if you'd like, for instance:

https://github.com/marketplacer/keychain-swift
