### ISSUE TITLE
Facebook returns AccessToken with no E-Mail-Information

### ISSUE THREAD

**Issue by quiKsilverItaly** [SimplicityMobile/Simplicity#29]
I did this: 

```
let facebook = Facebook()
facebook.scopes = ["email"]
        
Simplicity.login(facebook) { (accessToken, error) in
//do something
}
```

After getting the AccessToken back, I make a HTTP-Request with this URL: https://graph.facebook.com/me?access_token= and get following result:

> {
>    "name": "My Name",
>    "id": "10972xxxxxxx718"
> }

No E-Mail information.. any ideas?
I also tried the default way: `Simplicity.login(Facebook())`

**Comment by quiKsilverItaly** [comment]
Sorry the next time I will use Google first. 

Solution: https://graph.facebook.com/me?fields=email&access_token=[INSERT_TOKEN]

**Comment by edjiang** [comment]
Glad you figured it out!
