### ISSUE TITLE
Objective-c

### ISSUE THREAD

**Issue by FreudGit** [SimplicityMobile/Simplicity#32]
Hi

I'm trying to make it work using objective-c.

Cannot found hot to call this using Obj-C syntax.  Can i please ask if someone have done it with success?

Thanks!

Simplicity.login(Facebook()) { (accessToken, error) in
  // Handle access token here
}

**Comment by edjiang** [comment]
Unfortunately, this library is not objective-c compatible, since you do have to put some extra work into avoiding newer Swift features, etc. Sorry!
