### ISSUE TITLE
Carthage Compatible!

### ISSUE THREAD

**Issue by Dershowitz011** [SimplicityMobile/Simplicity#4]
Please share the scheme and update this. Carthage is unable to build a scheme for this.

**Comment by edjiang** [comment]
Thanks for letting me know! I've only really used Cocoapods and Swift Package Manager, so didn't realize that Carthage was more setup than pointing at a repo & tag. Sorry about that! I'll get to this on Monday.

**Comment by edjiang** [comment]
Pushed a new tag, 1.0.1, that fixes this. Hope this helps!

**Comment by edjiang** [comment]
```
Edwards-Work-MacBook:Test 5 edjiang$ carthage update
*** Fetching Simplicity
*** Checking out Simplicity at "1.0.1"
*** xcodebuild output can be found in /var/folders/6t/tw4wtw0n1fg3_fsfq79npj040000gn/T/carthage-xcodebuild.9Tjbho.log
*** Building scheme "Simplicity" in Simplicity.xcodeproj
```
