### ISSUE TITLE
Add Track App Installs and App Opens!! 

### ISSUE THREAD

**Issue by Dershowitz011** [SimplicityMobile/Simplicity#5]
This would be a brilliant feature if you could add it in this repo. Thanks!! 

> App Events let you measure installs on your mobile app ads, create high value audiences for targeting, and view analytics including user demographics. To log an app activation event, first, import the Facebook SDK in your AppDelegate.m file:
#import <FBSDKCoreKit/FBSDKCoreKit.h>
Next, add the following to your app delegate:
- - (void)applicationDidBecomeActive:(UIApplication *)application {
  [FBSDKAppEvents activateApp];
}
- - (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions {
  [[FBSDKApplicationDelegate sharedInstance] application:application
                           didFinishLaunchingWithOptions:launchOptions];
  return YES;
}
- - (BOOL)application:(UIApplication *)application
            openURL:(NSURL *)url
  sourceApplication:(NSString *)sourceApplication
         annotation:(id)annotation {
  return [[FBSDKApplicationDelegate sharedInstance] application:application
                                                         openURL:url
                                               sourceApplication:sourceApplication
                                                      annotation:annotation];
}
When people install or engage with your app, you'll see this data reflected in your app's Insights dashboard.

**Comment by edjiang** [comment]
Thanks for the suggestion! 

FB does have some great things including App Analytics, but the goal for Simplicity is for it to be the easiest way to do login across multiple platforms, and be solely focused on that goal. Adding app events would be super useful as an alternative to the Facebook SDK, but it would complicate setup, and the FB SDK already exists. 

So I'll be closing this request -- but feel free to fork & add it in yourself!
